import { Place, Report, UserProfile, AppNotification } from '@/types/accessibility';

export const MOCK_PLACES: Place[] = [
  {
    id: 'place-1',
    name: 'Central Community Library',
    category: 'Public Library & Learning Hub',
    address: '450 Civic Center Plaza, Downtown',
    lat: 37.7749,
    lng: -122.4194,
    features: {
      ramp: true,
      elevator: true,
      toilet: true,
      parking: true,
      stepFree: true,
      tactilePaving: true,
      automaticDoor: true,
    },
    photos: [
      'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1568667256549-094345857637?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 5,
    disputeCount: 0,
    status: 'verified',
    saved: true,
    description: 'Fully accessible civic center with automated sliding doors, wide elevator corridors, and tactile audio floor guides.',
  },
  {
    id: 'place-2',
    name: 'Metropolitan Train Station',
    category: 'Transit Hub',
    address: '100 Grand Avenue, Central District',
    lat: 37.7833,
    lng: -122.4167,
    features: {
      ramp: true,
      elevator: false,
      toilet: true,
      parking: false,
      stepFree: false,
      tactilePaving: true,
      automaticDoor: true,
    },
    photos: [
      'https://images.unsplash.com/photo-1517649763962-0c623266010b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 1,
    disputeCount: 0,
    status: 'pending',
    saved: true,
    description: 'Busy transit station. Main floor ramp is active, but Platform 2 elevator is currently undergoing maintenance.',
  },
  {
    id: 'place-3',
    name: 'City Botanical Gardens',
    category: 'Public Park & Leisure',
    address: '800 Greenery Way, East Park',
    lat: 37.769,
    lng: -122.446,
    features: {
      ramp: false,
      elevator: false,
      toilet: false,
      parking: true,
      stepFree: false,
      tactilePaving: false,
      automaticDoor: false,
    },
    photos: [
      'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 0,
    disputeCount: 2,
    status: 'disputed',
    saved: false,
    description: 'Historic entrance has steep cobblestone steps. Accessible side ramp route was claimed but reported blocked.',
  },
  {
    id: 'place-4',
    name: 'Civic Arts Center',
    category: 'Cultural Venue',
    address: '320 Theater Way, Arts Quarter',
    lat: 37.78,
    lng: -122.408,
    features: {
      ramp: true,
      elevator: true,
      toilet: true,
      parking: true,
      stepFree: true,
      tactilePaving: false,
      automaticDoor: true,
    },
    photos: [
      'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 4,
    disputeCount: 0,
    status: 'verified',
    saved: false,
    description: 'Modern auditorium with designated wheelchair seating spaces, ramped entrance, and accessible braille signage.',
  },
  {
    id: 'place-5',
    name: 'Riverside Promenade Restroom',
    category: 'Public Restroom & Amenity',
    address: 'Pier 14 Boardwalk',
    lat: 37.792,
    lng: -122.391,
    features: {
      ramp: true,
      elevator: false,
      toilet: true,
      parking: false,
      stepFree: true,
      tactilePaving: true,
      automaticDoor: false,
    },
    photos: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 2,
    disputeCount: 0,
    status: 'pending',
    saved: true,
    description: 'Standalone accessible family restroom on the waterfront boardwalk with grab bars and adult changing table.',
  },
];

export const MOCK_REPORTS: Report[] = [
  {
    id: 'report-1',
    placeId: 'place-2',
    placeName: 'Metropolitan Train Station',
    submitterName: 'Sarah Chen (Mobility Advocate)',
    submitterAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    timestamp: '10 mins ago',
    note: 'Platform 2 elevator out of service. High-priority issue for wheelchair commuters taking north-bound trains.',
    featuresReported: {
      ramp: true,
      elevator: false,
      toilet: true,
    },
    photos: [
      'https://images.unsplash.com/photo-1517649763962-0c623266010b?auto=format&fit=crop&w=800&q=80',
    ],
    priority: 'High',
    confirmCount: 1,
    disputeCount: 0,
    status: 'pending',
  },
  {
    id: 'report-2',
    placeId: 'place-3',
    placeName: 'City Botanical Gardens',
    submitterName: 'David Miller',
    submitterAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    timestamp: '1 hour ago',
    note: 'Side ramp gated and locked shut today. Main entrance still has 8 steep stone steps without handrails.',
    featuresReported: {
      ramp: false,
      stepFree: false,
    },
    photos: [
      'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=800&q=80',
    ],
    priority: 'High',
    confirmCount: 0,
    disputeCount: 2,
    status: 'disputed',
  },
  {
    id: 'report-3',
    placeId: 'place-5',
    placeName: 'Riverside Promenade Restroom',
    submitterName: 'Elena Rostova',
    submitterAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80',
    timestamp: '2 hours ago',
    note: 'New power automatic door opener installed yesterday! Fully functional and easy keycard press access.',
    featuresReported: {
      toilet: true,
      automaticDoor: true,
      stepFree: true,
    },
    photos: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    ],
    priority: 'Medium',
    confirmCount: 2,
    disputeCount: 0,
    status: 'pending',
  },
];

export const INITIAL_USER_PROFILE: UserProfile = {
  name: 'Alex Morgan',
  email: 'alex.morgan@accessibility.org',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  hasDisability: true,
  disabilityType: 'Manual Wheelchair User',
  preferences: {
    requireRamp: true,
    requireElevator: true,
    requireAccessibleToilet: true,
    requireStepFree: true,
  },
};

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    placeId: 'place-1',
    placeName: 'Central Community Library',
    oldStatus: 'pending',
    newStatus: 'verified',
    message: 'Central Community Library verified ramp & elevator access (5 community confirmations).',
    timestamp: 'Yesterday at 4:30 PM',
    read: false,
  },
  {
    id: 'notif-2',
    placeId: 'place-2',
    placeName: 'Metropolitan Train Station',
    oldStatus: 'verified',
    newStatus: 'pending',
    message: 'New report submitted for Metropolitan Train Station: Platform 2 elevator offline.',
    timestamp: '2 hours ago',
    read: false,
  },
];
