import { PlaceCategory } from '@/types/categoryPlaces';

export const PLACE_CATEGORIES: PlaceCategory[] = [
  {
    id: 'mall',
    name: 'Shopping Mall',
    shortLabel: 'Mall',
    icon: 'cart-outline',
    color: '#8B5CF6',
    bgColor: '#F5F3FF',
    description: 'Malls, shopping centers, department stores & retail plazas',
  },
  {
    id: 'library',
    name: 'Public Library',
    shortLabel: 'Library',
    icon: 'book-outline',
    color: '#3B82F6',
    bgColor: '#EFF6FF',
    description: 'Civic libraries, reading rooms & digital learning hubs',
  },
  {
    id: 'transit',
    name: 'Transit Hub',
    shortLabel: 'Transit',
    icon: 'subway-outline',
    color: '#06B6D4',
    bgColor: '#ECFEFF',
    description: 'Train stations, metro interchanges, terminals & stops',
  },
  {
    id: 'park',
    name: 'Public Park',
    shortLabel: 'Park',
    icon: 'leaf-outline',
    color: '#10B981',
    bgColor: '#ECFDF5',
    description: 'Public gardens, recreation grounds & accessible walkways',
  },
  {
    id: 'healthcare',
    name: 'Healthcare & Clinic',
    shortLabel: 'Health',
    icon: 'medkit-outline',
    color: '#EF4444',
    bgColor: '#FEF2F2',
    description: 'Hospitals, medical centers, clinics & pharmacies',
  },
  {
    id: 'civic',
    name: 'Civic & Government',
    shortLabel: 'Civic',
    icon: 'business-outline',
    color: '#F59E0B',
    bgColor: '#FFFBEB',
    description: 'Municipal buildings, post offices, civic halls & courts',
  },
  {
    id: 'dining',
    name: 'Café & Restaurant',
    shortLabel: 'Dining',
    icon: 'restaurant-outline',
    color: '#EC4899',
    bgColor: '#FDF2F8',
    description: 'Accessible eateries, food courts, restaurants & cafés',
  },
];
