import { SavedCategoryPlace } from '@/types/categoryPlaces';

export const SAVED_DATABASE_PLACES: SavedCategoryPlace[] = [
  // ── Shopping Malls ──────────────────────────────────────────────────
  {
    id: 'db-mall-1',
    name: 'Grand City Galleria Mall',
    categoryId: 'mall',
    category: 'Shopping Mall',
    address: '500 Central Boulevard, Downtown',
    lat: 6.9275,
    lng: 79.8615,
    features: {
      ramp: true,
      elevator: true,
      toilet: true,
      parking: true,
      stepFree: true,
      tactilePaving: true,
      automaticDoor: true,
    },
    photos: [
      'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 14,
    disputeCount: 0,
    status: 'verified',
    saved: true,
    description: 'Multi-story shopping mall with dedicated elevator towers, automatic sliding doors, step-free concourses, and designated accessible parking bays.',
  },
  {
    id: 'db-mall-2',
    name: 'Westfield Accessibility Plaza & Mall',
    categoryId: 'mall',
    category: 'Shopping Mall',
    address: '120 Commercial Avenue, West Quarter',
    lat: 6.9312,
    lng: 79.8540,
    features: {
      ramp: true,
      elevator: true,
      toilet: true,
      parking: true,
      stepFree: true,
      tactilePaving: false,
      automaticDoor: true,
    },
    photos: [
      'https://images.unsplash.com/photo-1567449303078-57ad995bd301?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 8,
    disputeCount: 1,
    status: 'verified',
    saved: true,
    description: 'Modern shopping plaza with wide ramp access, accessible rest spaces, and spacious accessible restrooms on every floor.',
  },
  {
    id: 'db-mall-3',
    name: 'Metro Walk Center & Retail Hub',
    categoryId: 'mall',
    category: 'Shopping Mall',
    address: '88 Promenade Street, East District',
    lat: 6.9201,
    lng: 79.8680,
    features: {
      ramp: true,
      elevator: false,
      toilet: true,
      parking: true,
      stepFree: true,
      tactilePaving: false,
      automaticDoor: true,
    },
    photos: [
      'https://images.unsplash.com/photo-1555529771-835f59fc5efe?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 4,
    disputeCount: 0,
    status: 'pending',
    saved: true,
    description: 'Single-level accessible retail complex. Main entrance features low-slope ramps and automatic sensor doors.',
  },

  // ── Public Libraries ────────────────────────────────────────────────
  {
    id: 'db-lib-1',
    name: 'Central Community Library',
    categoryId: 'library',
    category: 'Public Library',
    address: '450 Civic Center Plaza, Downtown',
    lat: 6.9271,
    lng: 79.8612,
    features: {
      ramp: true,
      elevator: true,
      toilet: true,
      parking: true,
      stepFree: true,
      tactilePaving: true,
      automaticDoor: true,
    },
    photos: [
      'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 19,
    disputeCount: 0,
    status: 'verified',
    saved: true,
    description: 'Full barrier-free library featuring tactile paving corridors, audio book assistance, accessible counters, and elevator access to all research floors.',
  },
  {
    id: 'db-lib-2',
    name: 'West End Public Media Library',
    categoryId: 'library',
    category: 'Public Library',
    address: '14 Horizon Way, West Side',
    lat: 6.9150,
    lng: 79.8520,
    features: {
      ramp: true,
      elevator: false,
      toilet: true,
      parking: false,
      stepFree: true,
      tactilePaving: true,
      automaticDoor: false,
    },
    photos: [
      'https://images.unsplash.com/photo-1568667256549-094345857637?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 6,
    disputeCount: 0,
    status: 'verified',
    saved: true,
    description: 'Ground floor community reading hall with wide study aisles and wheelchair-accessible digital workstations.',
  },

  // ── Transit Hubs ────────────────────────────────────────────────────
  {
    id: 'db-transit-1',
    name: 'Metropolitan Train Station',
    categoryId: 'transit',
    category: 'Transit Hub',
    address: '100 Grand Avenue, Central District',
    lat: 6.9340,
    lng: 79.8500,
    features: {
      ramp: true,
      elevator: true,
      toilet: true,
      parking: true,
      stepFree: true,
      tactilePaving: true,
      automaticDoor: true,
    },
    photos: [
      'https://images.unsplash.com/photo-1517649763962-0c623266010b?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 22,
    disputeCount: 1,
    status: 'verified',
    saved: true,
    description: 'Major railway hub with level platform boarding on Platforms 1-3, audio announcements, and tactile warning strips.',
  },
  {
    id: 'db-transit-2',
    name: 'Central Express Bus Terminal',
    categoryId: 'transit',
    category: 'Transit Hub',
    address: '240 Terminal Way, North Interchange',
    lat: 6.9380,
    lng: 79.8590,
    features: {
      ramp: true,
      elevator: false,
      toilet: true,
      parking: true,
      stepFree: true,
      tactilePaving: true,
      automaticDoor: false,
    },
    photos: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 7,
    disputeCount: 0,
    status: 'pending',
    saved: true,
    description: 'Covered bus bays with zero-step curb transitions, bench rest areas, and clear route displays.',
  },

  // ── Public Parks ────────────────────────────────────────────────────
  {
    id: 'db-park-1',
    name: 'City Botanical Gardens & Parkland',
    categoryId: 'park',
    category: 'Public Park',
    address: '800 Greenery Way, East Park',
    lat: 6.9120,
    lng: 79.8660,
    features: {
      ramp: true,
      elevator: false,
      toilet: true,
      parking: true,
      stepFree: true,
      tactilePaving: false,
      automaticDoor: false,
    },
    photos: [
      'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 11,
    disputeCount: 0,
    status: 'verified',
    saved: true,
    description: 'Paved trail loop with gradual inclines, rest benches every 50 meters, and accessible public restrooms at North Gate.',
  },
  {
    id: 'db-park-2',
    name: 'Waterfront Promenade Greenery',
    categoryId: 'park',
    category: 'Public Park',
    address: 'Pier 12 Coastline Walk',
    lat: 6.9240,
    lng: 79.8450,
    features: {
      ramp: true,
      elevator: false,
      toilet: true,
      parking: false,
      stepFree: true,
      tactilePaving: true,
      automaticDoor: false,
    },
    photos: [
      'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 5,
    disputeCount: 0,
    status: 'verified',
    saved: true,
    description: 'Open oceanfront recreational space with flat concrete paths and barrier-free view decks.',
  },

  // ── Healthcare & Clinic ─────────────────────────────────────────────
  {
    id: 'db-health-1',
    name: 'Metropolitan General Hospital',
    categoryId: 'healthcare',
    category: 'Healthcare & Clinic',
    address: '700 Medical Drive, Health Quarter',
    lat: 6.9220,
    lng: 79.8730,
    features: {
      ramp: true,
      elevator: true,
      toilet: true,
      parking: true,
      stepFree: true,
      tactilePaving: true,
      automaticDoor: true,
    },
    photos: [
      'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 30,
    disputeCount: 0,
    status: 'verified',
    saved: true,
    description: 'Comprehensive medical campus with 24/7 accessible entrance, dedicated drop-off ramp, automatic sliding doors, and wheelchair loan station.',
  },
  {
    id: 'db-health-2',
    name: 'Community Health & Rehabilitation Clinic',
    categoryId: 'healthcare',
    category: 'Healthcare & Clinic',
    address: '33 Care Boulevard, South Ward',
    lat: 6.9080,
    lng: 79.8620,
    features: {
      ramp: true,
      elevator: true,
      toilet: true,
      parking: true,
      stepFree: true,
      tactilePaving: false,
      automaticDoor: true,
    },
    photos: [
      'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 9,
    disputeCount: 0,
    status: 'verified',
    saved: true,
    description: 'Specialized clinic designed specifically for physical therapy with zero thresholds and wide doorframes.',
  },

  // ── Civic & Government ──────────────────────────────────────────────
  {
    id: 'db-civic-1',
    name: 'Civic Arts & Cultural Center',
    categoryId: 'civic',
    category: 'Civic & Government',
    address: '320 Theater Way, Arts Quarter',
    lat: 6.9180,
    lng: 79.8600,
    features: {
      ramp: true,
      elevator: true,
      toilet: true,
      parking: true,
      stepFree: true,
      tactilePaving: true,
      automaticDoor: true,
    },
    photos: [
      'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 16,
    disputeCount: 0,
    status: 'verified',
    saved: true,
    description: 'Public community hall with assistive listening systems, wheelchair seating zones, and power-assisted entrance doors.',
  },

  // ── Café & Dining ───────────────────────────────────────────────────
  {
    id: 'db-dining-1',
    name: 'Green Garden Accessible Café & Bistro',
    categoryId: 'dining',
    category: 'Café & Restaurant',
    address: '45 Blossom Lane, Central Gardens',
    lat: 6.9260,
    lng: 79.8640,
    features: {
      ramp: true,
      elevator: false,
      toilet: true,
      parking: false,
      stepFree: true,
      tactilePaving: false,
      automaticDoor: false,
    },
    photos: [
      'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
    ],
    confirmCount: 12,
    disputeCount: 0,
    status: 'verified',
    saved: true,
    description: 'Ground-floor café featuring wide aisles between tables, lowered ordering counter, and braille menus.',
  },
];
